config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  
  get '/signup'  =>  'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  get '/logout' => 'sessions#destroy'



  resources :artists
  resources :concerts do
    resources :experiences, only: [:new, :create, :index]
    resources :artists, only: [:new, :create, :index]
  end
  resources :experiences
  resources :users do
    resources :concerts, only: [:new, :create, :index]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    belongs_to :concert
end

app/models/concert.rb
class Concert < ApplicationRecord
    has_many :experiences
    has_many :artists
    has_many :users, through: :experience
end

app/models/experience.rb
class Experience < ApplicationRecord
    belongs_to :user
    belongs_to :concert
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :expeiences
    has_many :concerts, through: :experience
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private
    
      def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
      end

      def logged_in?
        !!session[:user_id]
      end

      def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
      end
  end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
#genres = artists

def index
    @artists = Artist.all
end

def new
    @artists = Artist.new
end

def create
    @artists = Artist.new(artists_params)
    if @artists.save
        redirect_to concerts_path
    else
        render :new 
    end
end

def show
    @artists = Artist.find(params[:id])
end

private

def artist_params
    params.require(:artists).permit(:name, :genre)
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

    def index
        @concerts = Concert.all
       # if params[:user_id]
       #     @concert = User.find(params[:user_id]).concerts
        #    flash.now[:danger] = "You haven't added any concerts yet!" if @concerts.empty?
        #end
    end

    def new
        @concerts = Concert.new
       # @concert.review.build
    end

    def create
        @concerts = Concert.create(concert_params)
        if @concerts.save
            redirect_to concerts_path
        else
            render :new 
        end
    end

    def show
        @concerts = Concert.find(params[:id])
    end

    private

    def concert_params
        params.require(:concert).permit(:city, :state, :venue, :date, :artist)
    end
    
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
    #experiences = review
    before_action :redirect_if_not_logged_in
    before_action :set_experience, only: [:show, :edit, :update]
    before_action :redirect_if_not_experience_author, only: [:edit, :update]
 
   def index
     if params[:concert_id] && @concert = Concert.find_by_id(params[:concert_id])
        @experiences = @concert.experiences
     else
       @error = "That post doesn't exist" if params[:post_id]
       @experiences = Experience.all
     end
   end
 
   def new
     
     if params[:concert_id] && @concert = Concert.find_by_id(params[:concert_id])
       @experience = @concert.experience.build
     else
       @error = "That post doesn't exist" if params[:concert_id]
       @experience = Experience.new
     end
   end
 
   def create
     @experience = current_user.experience.build(experience_params)
     if @experience.save
       redirect_to experiences_path
     else
       render :new
     end
   end
 
 
   def show
   end
 
   def edit
   end
 
   def update
     if @experience.update(experience_params)
       redirect_to experience_path(@experience)
     else
       render :edit
     end
   end
 
   private
 
   def experience_params
     params.require(:experience).permit(:comment, :rating, :concert_id, :user_id)
   end
 
   def set_experience
     @experience = Experience.find_by(id: params[:id])
     if !@experience
       flash[:message] = "Experience was not found"
       redirect_to experiences_path
     end
   end
 
   def redirect_if_not_experience_author
      redirect_to experiences_path if @experience.user != current_user
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def destroy
        session.clear
        redirect_to root_path
      end
    
      def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
          session[:user_id] = user.id
          redirect_to user_path(user)
        else
          flash[:message] = "Incorrect login info, please try again"
          redirect_to "/login"
        end
      end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user_id
            redirect_to @user
        else
            render :new 
        end
    end

    def show
        @user = User.find_by_id(params[:id])
        redirect_to '/' if !@user
    end
    
    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concerts/index.html.erb
<h1>All Concerts</h1>
 
<table>
 
  <tbody>
    <% @concerts.map do |c|%>
      <tr>
        <td><%= c.artist %></td>
        <td><%= c.venue %></td>
        <td><%= c.city %></td>
        <td><%= c.state %></td>
        <td><%= c.date %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New concert", new_concert_path %>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<%= form_for(@concerts) do |f|%>
    <%= f.label :artist %>
    <%= f.text_field :artist %>

    <%= f.label :venue %>
    <%= f.text_field :venue %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.date_field :date, class: 'form-control' %>
    
    <%= f.submit %>

<% end %>

app/views/experiences/index.html.erb
<% if @concert %>
  <h1>Comments for <%= @concert.venue%></h1>
<% else %>
  <h1>All Comments</h1>
<% end %>

<ul>
<% @experiences.each do |c|%>
  <li><%= c.user.username%> says "<%= c.comment%>" about this post: <strong><%= link_to c.concert.name, concert_path(c.concert_id) %></strong></li>
<% end %>
</ul>

app/views/experiences/new.html.erb
<% if @experience.post %>
<h1>New Experience for <%= @experience.concert.name %>!</h1>
<% else %>
<h1>New Comment!</h1>
<% end %>



<%= form_for([@experience.concert,@experience]) do |f|%>

    <% if !@experience.concert %>
        <%= f.label :concert %>
        <%= f.collection_select :concert_id, Concert.all, :id, :name %>
    <% else %>
        <%= f.hidden_field :concert_id %>
    <% end %>

  <%= f.label :venue, :city, :state %>
  <%= f.text_field :venue, :city, :state %>


  <%= f.submit %>

<% end %>

app/views/experiences/show.html.erb
<h2><%= @experience.comment%> - <%= @comment.user.username%></h2>

<% if @experience.user == current_user %>
  <%= link_to "Edit Experience", edit_experience_path(@experience)%>
<% end %>

<h4>Read about the concert here: <%= link_to @experience.concert.titlerating, concert_path(@experience.concert_id) %></h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConcertExperience</title>
  </head>

  <body>

    <div>
      <% if logged_in?%>
        <%= link_to "Add a Concert", new_concert_path %> |
        <%= link_to "All Concerts", concerts_path %> |
        <%= link_to "Logout", logout_path, method:"delete"%>

      <% else %>
        <%=link_to "Sign Up", signup_path %> |
        <%=link_to "Log In", login_path %>
      <% end %>

    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user, url:'/signup') do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
     <br>
    <%= f.label :email%>
    <%= f.email_field :email %>
    <br>
     <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
     <br>


    <%= f.submit "Submit" %>

<% end %>


app/views/users/show.html.erb
<h1>Welcome <%=@user.username %></h1>

<%= link_to "Logout", logout_path, method:"delete"%>